### ISSUE TITLE
Failure to start with SDK 2.1.1 / Alfresco 5.0.d

### ISSUE THREAD

**Issue by binduwavell** [jpotts/share-site-creators#29]
Here is the error I receive when starting the repo with this extension:

```
2016-11-05 14:45:09,716  ERROR [web.context.ContextLoader] [localhost-startStop-1] Context initialization failed
 org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'SiteService_security' defined in class path resource [alfresco/module/share-site-creators-repo/context/service-context.xml]: Initialization of bean failed; nested exception is org.springframework.beans.TypeMismatchException: Failed to convert property value of type 'java.lang.String' to required type 'net.sf.acegisecurity.intercept.method.MethodDefinitionSource' for property 'objectDefinitionSource'; nested exception is java.lang.IllegalArgumentException: Couldn't find method 'listSiteMemberships' on interface org.alfresco.service.cmr.site.SiteService
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:529)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:458)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:293)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:223)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:290)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:191)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:633)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:932)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:479)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:410)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:306)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:112)
	at org.alfresco.web.app.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:63)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4939)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5434)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.springframework.beans.TypeMismatchException: Failed to convert property value of type 'java.lang.String' to required type 'net.sf.acegisecurity.intercept.method.MethodDefinitionSource' for property 'objectDefinitionSource'; nested exception is java.lang.IllegalArgumentException: Couldn't find method 'listSiteMemberships' on interface org.alfresco.service.cmr.site.SiteService
	at org.springframework.beans.BeanWrapperImpl.convertIfNecessary(BeanWrapperImpl.java:468)
	at org.springframework.beans.BeanWrapperImpl.convertForProperty(BeanWrapperImpl.java:494)
	at org.springframework.beans.BeanWrapperImpl.convertForProperty(BeanWrapperImpl.java:488)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.convertForProperty(AbstractAutowireCapableBeanFactory.java:1464)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1423)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1159)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:519)
	... 21 more
Caused by: java.lang.IllegalArgumentException: Couldn't find method 'listSiteMemberships' on interface org.alfresco.service.cmr.site.SiteService
	at net.sf.acegisecurity.intercept.method.MethodDefinitionMap.addSecureMethod(MethodDefinitionMap.java:179)
	at net.sf.acegisecurity.intercept.method.MethodDefinitionMap.addSecureMethod(MethodDefinitionMap.java:142)
	at net.sf.acegisecurity.intercept.method.MethodDefinitionSourceEditor.setAsText(MethodDefinitionSourceEditor.java:76)
	at org.springframework.beans.TypeConverterDelegate.doConvertTextValue(TypeConverterDelegate.java:455)
	at org.springframework.beans.TypeConverterDelegate.doConvertValue(TypeConverterDelegate.java:427)
	at org.springframework.beans.TypeConverterDelegate.convertIfNecessary(TypeConverterDelegate.java:181)
	at org.springframework.beans.BeanWrapperImpl.convertIfNecessary(BeanWrapperImpl.java:448)
	... 27 more
```

**Comment by binduwavell** [comment]
Also failing with SDK 2.1.1 enterprise 5.0.1

**Comment by binduwavell** [comment]
FYI. I had success with SDK 2.2.0, Alfresco 5.1.e and 5.1.1.

**Comment by jpotts** [comment]
You should use an older version of the module with an older version of Alfresco. I make no effort to maintain backwards compatibility.
